version: 0.2
phases:
  pre_build:
    commands:
      # Install Snyk
      - echo Install Snyk
      - curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.210.0/snyk-linux"
      - chmod -R +x ./snyk
      # Snyk auth
      # - ./snyk config set api="$SNYK_AUTH_TOKEN"
      # Build Docker image for testing
      - sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
      - sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
      - sudo dockerd
      - echo Build client and backend docker images for testing...
      - docker build -t 216880/react-test -f ./client/Dockerfile.dev ./client
      - docker build -t 216880/nodejs-test -f ./backend/Dockerfile.dev ./backend
  build:
    commands:
      - echo Build started on `date`
      # Run tests with built Docker images
      - echo Run react tests...
      - docker run -e CI=true 216880/react-test
      - echo Run nodejs tests...
      - docker run -e CI=true 216880/nodejs-test
      # Scan Docker image with Snyk
      ## Client
      ## Run test for security vulernabilities
      # - ./snyk test --severity-threshold=medium --docker 216880/react-test:latest --file=./client/Dockerfile.dev
      ## Setup continuous monitoring
      # - ./snyk monitor --docker 216880/react-test:latest --file=./client/Dockerfile.dev
      ## Backend
      ## Run test for security vulernabilities
      # - ./snyk test --severity-threshold=medium --docker 216880/nodejs-test:latest --file=./backend/Dockerfile.dev
      ## Setup continuous monitoring
      # - ./snyk monitor --docker 216880/nodejs-test:latest --file=./backend/Dockerfile.dev
      # Build the Docker images
      - echo Building the production Docker image...
      - docker build -t psoir_app/psoir-app-client ./client
      - docker build -t psoir_app/psoir-app-backend ./backend
      - docker build -t psoir_app/psoir-app-nginx ./nginx
      # Log in to the Docker CLI
      - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  post_build:
    commands:
      # Take these images and push them to Docker hub
      - echo Pushing the Docker images...
      - docker push 216880/psoir-app-client
      - docker push 216880/psoir-app-backend
      - docker push 216880/psoir-app-nginx