version: 0.2
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - curl -fsSL https://get.docker.com/ -o get-docker.sh
      
  pre_build:
    commands:
      - echo Install Snyk
      - curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.210.0/snyk-linux"
      - chmod -R +x ./snyk
      - echo Build client and backend docker images for testing...
      - docker build -t 216880/react-test -f ./client/Dockerfile.dev ./client
      - docker build -t 216880/nodejs-test -f ./backend/Dockerfile.dev ./backend
  build:
    commands:
      - echo Build started on `date`
      - echo Run react tests...
      - docker run -e CI=true 216880/react-test
      - echo Run nodejs tests...
      - docker run -e CI=true 216880/nodejs-test
      - echo Building the production Docker image...
      - docker build -t 216880/psoir-app-client ./client
      - docker build -t 216880/psoir-app-backend ./backend
      - docker build -t 216880/psoir-app-nginx ./nginx
      - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push 216880/psoir-app-client
      - docker push 216880/psoir-app-backend
      - docker push 216880/psoir-app-nginx
artifacts:
  files:
    - '**/*'