version: "3.3"
services:
  nginx:
    image: psoir_app/psoir-app-nginx
    depends_on:
      - client
      - backend
    restart: always # because it is routing traffic to our entire app
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
  client:
    image: psoir_app/psoir-app-client
    build:
      context: ./client
      dockerfile: Dockerfile
    #ports:
    #  - '3000:3000'
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    restart: on-failure
    container_name: client
  backend:
    image: psoir_app/psoir-app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    #ports:
    #  - '3001:3001'
    restart: on-failure
    container_name: backend
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    env_file:
      - ./env/backend.env
  mongo:
    image: 'mongo'
    container_name: 'mongo-db'
    ports:
      - '27017-27019:27017-27019'
    volumes: 
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/mongo-volume:/data/db
    env_file:
      - ./env/mongo.env